"""baseline: full schema as of Wave 5 / Workstream B (17 tables)

Captures the complete pre-Alembic schema (everything `create_all` had ever
produced across waves 1-4 plus two fix batches) as the starting point for
Alembic-managed migrations. Autogenerated against an empty scratch SQLite
database via `server.db.Base.metadata` (all models registered through
`import server.models`) -- see docs/migrations.md. `server/db_migrate.py`
stamps any existing pre-Alembic deployment straight to `head` without ever
re-running this upgrade() against a database that already has these tables
(see `ensure_schema` case 2).

Revision ID: 0001
Revises:
Create Date: 2026-07-11 10:16:08.166722

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_agent_id', sa.String(length=36), nullable=False),
    sa.Column('target_agent_id', sa.String(length=36), nullable=False),
    sa.Column('connection_type', sa.String(length=32), nullable=False),
    sa.Column('shared_context', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_connections_source_agent_id'), ['source_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_connections_target_agent_id'), ['target_agent_id'], unique=False)

    op.create_table('agent_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('priority_override', sa.Integer(), nullable=True),
    sa.Column('config_override', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_skills_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('audit_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('retrieval_hits', sa.JSON(), nullable=True),
    sa.Column('llm_meta', sa.JSON(), nullable=True),
    sa.Column('tool_meta', sa.JSON(), nullable=True),
    sa.Column('workflow_meta', sa.JSON(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_traces_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_audit_traces_agent_timestamp', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_traces_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_traces_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_traces_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_traces_trace_id'), ['trace_id'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_state', sa.JSON(), nullable=True),
    sa.Column('collected_data', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('active_skill_id', sa.String(length=36), nullable=True),
    sa.Column('delegation_chain', sa.JSON(), nullable=True),
    sa.Column('parent_session_id', sa.String(length=36), nullable=True),
    sa.Column('shared_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_parent_session_id'), ['parent_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_conversation_sessions_user_tenant', ['user_id', 'tenant_id'], unique=False)

    op.create_table('event_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_knowledge_sources_tenant_name')
    )
    op.create_table('llm_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('short_answer', sa.Text(), nullable=True),
    sa.Column('expanded_answer', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('suggested_followups', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skill_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('execution_config', sa.JSON(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('managed_by', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.Text(), server_default='', nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_ms', sa.Integer(), nullable=False),
    sa.Column('is_async', sa.Boolean(), nullable=False),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('required_permission', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_retries >= 0', name='ck_tools_max_retries'),
    sa.CheckConstraint('timeout_ms > 0', name='ck_tools_timeout_ms'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('api_keys', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('llm_config_id', sa.String(length=36), nullable=True),
    sa.Column('response_config', sa.JSON(), nullable=True),
    sa.Column('risk_config', sa.JSON(), nullable=True),
    sa.Column('skill_routing_mode', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_agents_tenant_name')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=64), nullable=True),
    sa.Column('entity_key', sa.String(length=256), nullable=True),
    sa.Column('cached_score', sa.Float(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_entity_key'), ['entity_key'], unique=False)
        batch_op.create_index('ix_knowledge_chunks_source_domain', ['source_id', 'domain'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('tool_id', sa.String(length=36), nullable=True),
    sa.Column('tool_config', sa.JSON(), nullable=True),
    sa.Column('on_failure', sa.String(length=32), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('fallback_step_id', sa.String(length=36), nullable=True),
    sa.Column('requires_human_confirm', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('next_step_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('published_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_versions_wf_ver')
    )
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_versions_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_versions_workflow_id'))

    op.drop_table('workflow_versions')
    op.drop_table('workflow_steps')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_chunks_source_domain')
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_entity_key'))

    op.drop_table('knowledge_chunks')
    op.drop_table('agents')
    op.drop_table('workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    op.drop_table('tool_definitions')
    op.drop_table('skills')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    op.drop_table('llm_configs')
    op.drop_table('knowledge_sources')
    with op.batch_alter_table('event_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_subscriptions_tenant_id'))

    op.drop_table('event_subscriptions')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_sessions_user_tenant')
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_parent_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_agent_id'))

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('audit_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_traces_trace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_traces_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_traces_session_id'))
        batch_op.drop_index(batch_op.f('ix_audit_traces_event_type'))
        batch_op.drop_index('ix_audit_traces_agent_timestamp')
        batch_op.drop_index(batch_op.f('ix_audit_traces_agent_id'))

    op.drop_table('audit_traces')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('agent_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_agent_skills_agent_id'))

    op.drop_table('agent_skills')
    with op.batch_alter_table('agent_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_connections_target_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_connections_source_agent_id'))

    op.drop_table('agent_connections')
    # ### end Alembic commands ###
