export type IntegrationCopy = ReturnType<typeof getIntegrationCopy>;

export function getIntegrationCopy(isZh: boolean) {
  if (isZh) {
    return {
      eyebrow: '开发者接入',
      title: '接入中心',
      subtitle: '集中查看并联调客户应用、语音输入、外部工具、工作流 webhook 和审计 trace。',
      integrationMap: '集成地图',
      integrationDesc:
        '客户系统通过 invoke、stream、ASR API 调用 Aezab；Aezab 通过注册工具和工作流完成 webhook 调用客户系统。',
      sourceOfTruth: {
        title: '配置边界',
        description:
          'Agent Management 是 Agent 能力编排的主入口；Integrations 是开发接入和联调工作台。本页的 Bind to Agent 快捷操作会写回同一套 Agent Capabilities，不会生成第二套配置。',
      },
      bindingNote:
        '这里是开发联调快捷入口。绑定会保存到 Agent Capabilities；后续增删知识、工作流、工具时，仍可回到 Agent Management 统一管理。',
      customerAppFlow: {
        title: '客户 App 接入流程',
        description:
          '客户 App 不需要使用 Aezab Playground；它只需要消费 invoke 返回值，并按 workflow_card 渲染自己的表单。',
        steps: [
          '客户 App 把用户消息发送到 /invoke。',
          '如果返回 short_answer，直接展示给用户。',
          '如果返回 workflow_card.fields，按字段类型渲染 App 自己的表单。',
          '用户提交后，用同一个 session_id + form_data 再调用 /invoke。',
          '流程完成后，读取 workflow_card.collected_data 展示结果，或等待 webhook 回写客户系统。',
          '出问题时，用 trace_id 到 Audit 回放调用链。',
        ],
        workflowCardTitle: 'workflow_card 渲染约定',
        formSubmitTitle: 'session_id + form_data 继续流程',
      },
      sectionTitles: {
        liveInvokeTest: '在线调用测试',
        clientSnippets: '客户端接入示例',
        responseContract: '响应结构约定',
      },
      tabs: {
        inbound: '入站 API',
        outbound: '出站工具',
        webhooks: '工作流 Webhook',
        traces: 'Trace 调试',
      },
      categoryHelp: {
        inbound: {
          summary: '客户自己的应用调用 Aezab Agent 的入口，例如网页、App、CRM、客服系统把用户消息发给 Agent。',
          howTo: '先创建 Agent，然后在本页选择 Agent，复制 invoke / stream 示例接入。',
        },
        asr: {
          summary: '语音输入转文字接口。客户应用上传音频，Aezab 返回文本，再把文本发给 Agent。',
          howTo: '在 Voice / ASR 配置中填 DashScope API Key，或部署自有 ASR 后填 host。',
        },
        outbound: {
          summary: 'Agent 主动调用客户原系统的能力，例如创建工单、查订单、更新 CRM。',
          howTo: '点击 Connect External API，填客户系统接口和参数 schema，测试后绑定给 Agent。',
        },
        webhooks: {
          summary: '工作流结束或关键步骤完成后通知客户系统，用于回写状态、同步结果。',
          howTo: '选择 Workflow 和 complete step，填 webhook URL 与 headers。',
        },
      },
      actions: {
        refresh: '刷新',
        openAudit: '打开审计',
        openDocs: '打开 /docs',
        openPlayground: '打开测试场',
        manage: '管理',
        copy: '复制',
        copied: '已复制',
        copyFailed: '复制失败',
        sendTest: '发送测试',
        connectExternalApi: '接入外部 API',
        configureWebhook: '配置工作流 Webhook',
        bindToolToAgent: '绑定 Agent',
        saveBinding: '保存绑定',
        testTool: '测试工具',
        saveTool: '保存工具',
        saveWebhook: '保存 Webhook',
      },
      fields: {
        apiBase: 'API Base',
        auth: '鉴权',
        swagger: 'Swagger',
        agent: 'Agent',
        triggerDescription: '触发说明',
        keywords: '关键词',
        selectAgent: '选择 Agent',
        answer: '回答',
        session: '会话',
        trace: 'Trace',
        workflow: '工作流',
        toolName: '工具名称',
        description: '描述',
        endpoint: '端点 URL',
        method: '方法',
        inputSchema: '输入 Schema',
        authType: '认证方式',
        authToken: '认证 Token',
        testInput: '测试输入 JSON',
        workflowSelect: '选择工作流',
        completeStep: '完成步骤',
        webhookUrl: 'Webhook URL',
        webhookHeaders: '请求头 JSON',
        eventType: '事件',
        latency: '延迟',
        status: '状态',
      },
      fieldHelp: {
        apiBase: '客户系统调用 Aezab 后端时使用的基础地址。部署到云上后应替换成客户自己的域名。',
        auth: '生产环境建议开启 API Key 或 Bearer Token。外部系统调用 invoke、ASR、工具测试接口时都应携带鉴权。',
        swagger: '/docs 是 FastAPI 自动生成的接口文档，适合开发人员查看完整请求参数和响应结构。',
      },
      empty: {
        noAgent: '请先创建 Agent',
        noTools: '还没有注册工具',
        noWorkflows: '还没有配置工作流',
        noTraces: '还没有 trace。发送一次测试消息即可生成。',
      },
      messages: {
        toolBoundToAgent: '工具已绑定到 Agent',
        bindToolFailed: '绑定 Agent 失败',
        loadFailed: '加载接入数据失败',
        selectAgentFirst: '请先选择 Agent',
        invokeFailed: '调用测试失败',
        invalidSchema: '输入 Schema 不是合法 JSON',
        invalidHeaders: '请求头不是合法 JSON',
        invalidTestInput: '测试输入不是合法 JSON',
        toolCreated: '工具已创建',
        toolTestPassed: '工具连通性测试通过',
        toolTestFailed: '工具连通性测试失败',
        webhookSaved: 'Webhook 已保存',
      },
    };
  }

  return {
    eyebrow: 'Developer Interface',
    title: 'Integrations',
    subtitle: 'Connect and test customer apps, voice input, outbound tools, workflow webhooks, and audit traces.',
    integrationMap: 'Integration map',
    integrationDesc:
      'Customer systems call Aezab through invoke, stream, and ASR APIs. Aezab calls customer systems through registered tools and workflow completion webhooks.',
    sourceOfTruth: {
      title: 'Configuration boundary',
      description:
        'Agent Management is the source of truth for agent capabilities. Integrations is a developer workbench for wiring, testing, and shortcut binding. Bind to Agent writes back to the same Agent Capabilities model; it does not create a second configuration system.',
    },
    bindingNote:
      'This is a developer shortcut. Bindings are saved into Agent Capabilities; use Agent Management later to review, remove, or reorganize knowledge, workflows, and tools.',
    customerAppFlow: {
      title: 'Customer App Integration Flow',
      description:
        'Customer apps do not need the Aezab Playground. They call invoke, render workflow cards in their own UI, and submit form_data with the same session.',
      steps: [
        'The customer app sends the user message to /invoke.',
        'If the response has short_answer, show it directly.',
        'If the response has workflow_card.fields, render the app form from those field definitions.',
        'When the user submits, call /invoke again with the same session_id + form_data.',
        'When completed, show workflow_card.collected_data or let the workflow webhook update the customer backend.',
        'Use trace_id in Audit when debugging the integration.',
      ],
      workflowCardTitle: 'workflow_card rendering contract',
      formSubmitTitle: 'Continue with session_id + form_data',
    },
    sectionTitles: {
      liveInvokeTest: 'Live Invoke Test',
      clientSnippets: 'Generated Client Snippets',
      responseContract: 'Response Contract',
    },
    tabs: {
      inbound: 'Inbound API',
      outbound: 'Outbound Tools',
      webhooks: 'Workflow Webhooks',
      traces: 'Trace & Debug',
    },
    categoryHelp: {
      inbound: {
        summary: 'Entry points for customer apps to call Aezab agents from websites, apps, CRMs, or support systems.',
        howTo: 'Create an agent, select it here, then copy the invoke or stream client snippet.',
      },
      asr: {
        summary: 'Audio-to-text input. Customer apps upload audio, Aezab returns text, then the app sends that text to an agent.',
        howTo: 'Configure a DashScope API key or point Aezab to a self-hosted ASR service.',
      },
      outbound: {
        summary: 'APIs the agent can call in the customer backend, such as creating tickets, checking orders, or updating CRM records.',
        howTo: 'Click Connect External API, define endpoint and input schema, test it, then bind it to an agent.',
      },
      webhooks: {
        summary: 'Callbacks from workflows back to customer systems when a flow reaches completion or a key step.',
        howTo: 'Select a workflow and completion step, then add the webhook URL and headers.',
      },
    },
    actions: {
      refresh: 'Refresh',
      openAudit: 'Open Audit',
      openDocs: 'Open /docs',
      openPlayground: 'Open Playground',
      manage: 'Manage',
      copy: 'Copy',
      copied: 'Copied',
      copyFailed: 'Copy failed',
      sendTest: 'Send Test',
      connectExternalApi: 'Connect External API',
      configureWebhook: 'Configure Workflow Webhook',
      testTool: 'Test Tool',
      bindToolToAgent: 'Bind to Agent',
      saveBinding: 'Save Binding',
      saveTool: 'Save Tool',
      saveWebhook: 'Save Webhook',
    },
    fields: {
      apiBase: 'API Base',
      auth: 'Auth',
      swagger: 'Swagger',
      selectAgent: 'Select Agent',
      answer: 'Answer',
      session: 'Session',
      trace: 'Trace',
      workflow: 'Workflow',
      toolName: 'Tool Name',
      description: 'Description',
      endpoint: 'Endpoint URL',
      method: 'Method',
      inputSchema: 'Input Schema',
      authType: 'Auth Type',
      authToken: 'Auth Token',
      agent: 'Agent',
      triggerDescription: 'When should the agent use it?',
      keywords: 'Keywords',
      testInput: 'Test Input JSON',
      workflowSelect: 'Select Workflow',
      completeStep: 'Completion Step',
      webhookUrl: 'Webhook URL',
      webhookHeaders: 'Headers JSON',
      eventType: 'Event',
      latency: 'Latency',
      status: 'Status',
    },
    fieldHelp: {
      apiBase: 'Base URL customer systems use to call the Aezab backend. In production this should be your deployed domain.',
      auth: 'Use API Key or Bearer Token in production. External invoke, ASR, and tool test calls should all be authenticated.',
      swagger: '/docs is the FastAPI-generated API reference for developers who need full request and response schemas.',
    },
    empty: {
      noAgent: 'Create an agent first',
      noTools: 'No tools registered yet',
      noWorkflows: 'No workflows configured yet',
      noTraces: 'No traces yet. Send a test message to create one.',
    },
    messages: {
      toolBoundToAgent: 'Tool bound to agent',
      bindToolFailed: 'Failed to bind tool to agent',
      loadFailed: 'Failed to load integration data',
      selectAgentFirst: 'Select an agent first',
      invokeFailed: 'Invoke test failed',
      invalidSchema: 'Input schema is not valid JSON',
      invalidHeaders: 'Headers are not valid JSON',
      invalidTestInput: 'Test input is not valid JSON',
      toolCreated: 'Tool created',
      toolTestPassed: 'Tool connectivity test passed',
      toolTestFailed: 'Tool connectivity test failed',
      webhookSaved: 'Webhook saved',
    },
  };
}
